### ISSUE TITLE
Feature - Baseline Prologue for AzureAdministratorsGroup

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine-plugin-azure#120]
## Expected Behavior

The baseline component should be suitable for all new products and tenants out of the box.

## Current Behavior

The baseline component currently requires a pseudo-stack to output the name and object-id of an Administrators group that should be granted access to the Azure Keyvault. The baseline component then grants access to the keyvault for that group. Without it, the keyvault cannot be double-checked through the Azure Portal as the user will not have permissions.

## Possible Solution

Update the existing Prologue template pass for the baseline to include a new administrators account and output the pseudo-stack prior to the template pass.

## Context

Prevented me from deploying the baseline component into a fresh environment.

**Comment by roleyfoley** [comment]
WE should also include this configuration in the cookie cutter template
