### ISSUE TITLE
Refactor - Azure ARM Function - Environment()

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine-plugin-azure#125]
## Expected Behavior

Endpoints should be readily accessible to ARM templates yet not unnecessarily hardcoded.

## Current Behavior

Hardcoded in hamlet code.

## Possible Solution

Utilise the new Azure ARM Function ["Environment"](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-deployment#environment)

## Context

This refactor is a part of keeping hamlet current and making use of each providers advantages as much as possible.

**Comment by roleyfoley** [comment]
Kill that - @RossMurr4y
