### ISSUE TITLE
Refactor - Update ARM Template Schema - 2019-04-01

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine-plugin-azure#126]
## Expected Behavior

Generated templates should stay as up-to-date as possible.

Latest: "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"

## Current Behavior

Not using latest schema.

## Possible Solution

Update schema to 2019-04-01 and test with existing cmdbs.

## Context

This is in line with keeping the hamlet provider as up-to-date as possible and making use of all the features that the provider has on offer.

**Comment by roleyfoley** [comment]
We pneed to make this ticket more specific, this could essentially be a ticket till the end of time
