### ISSUE TITLE
Refactor - Deployment Unit Per Resource Group

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine-plugin-azure#148]
## Expected Behavior

Each solution deployment-unit should have its own Resource Group to deploy into. This will be cleaner, and allow correct delete-mode of the `hamlet manage deployment` script which just deletes the entire RG.

## Current Behavior

Currently every deployment-unit is placed into the same resource group which is specified at deployment time, and they currently expect eachother to be in the same RG.

## Context

Deletion of deployment units has been a manual task, rather than being able to rely on hamlet.

**Comment by roleyfoley** [comment]
Done
