### ISSUE TITLE
Bug - Output Naming and Processing

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine-plugin-azure#169]
## Expected Behavior

Outputs that are defined on a given resource are assigned a type. The given type should be appended to the resourceId to form a new Id for that output. For example if the Id of a resource is `myXresourceXid` and it is assigned an output of type "url" then it should create an output titled `myXresourceXidXurl`. 

## Current Behaviour

Current behaviour, has the Id be appended by the value of the output, not the type. Whilst this still works, it creates unpredictable and unwieldy output titles.

Thus, the following example instead creates `myXresourceXidXpropertiesXfullyQualifiedDomainName` instead of `myXresourceXidXurl`.

`outputMappings = {
  URL_ATTRIBUTE_TYPE : {
    "Property" : "properties.fullyQualifiedDomainName"
  }
}
`
The value assigned to "Property" informs the engine what attribute on a given resource is to be output - it should remain the same. However naming of an output and retrieval of names should be based on the _ATTRIBUTE_TYPE, not the value of Property.

## Context

Uncovered in #168 
Though unwieldy, this works up until you need to retrieve an output with `getExistingReference()`. If you know you want the URL attribute, a call to `getExistingReference(id, URL_ATTRIBUTE_TYPE)` should be all that is required - however currently you instead need to pass in the value of property, which is different in every case. Instead of saying "give me the URL of this resource" you instead need to know how it retrieved the URL in the first place.

**Comment by roleyfoley** [comment]
We think @roleyfoley has fixed this, he can't remember so will have a look and confirm before closing

**Comment by roleyfoley** [comment]
We have confirmed this as closed and we revist if we need to
