### ISSUE TITLE
Baseline deployment should fail if user can't encrypt key

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-plugin-azure#179]
## Expected Behaviour
An exception is raised and deployment cancelled when the user running a template deployment doesn't have an access policy allowing them to access the Key Vault 

## Current Behaviour
The command line error messages is displayed in the console but the deployment continues

## Possible Solution
When an exception is raised in the encryption steps, exit and cancel the  deploy

## Steps to Reproduce (for bugs)
1. run a deployment of the baseline component without permissions assinged on the key vault

## Context
False positive result for the deployment

**Comment by roleyfoley** [comment]
Related to #120

**Comment by ken9ross** [comment]
https://github.com/hamlet-io/engine-plugin-azure/pull/215 includes checking the deployment user is a member of the group that has permissions on the keyVault and raising a fatal error if not
