### ISSUE TITLE
Enable Static Website on baseline storage account

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-plugin-azure#183]
## Expected Behaviour
when accessing content from an Azure Front Door through to an SPA the SPA site content is displayed

## Current Behaviour
Currently when setting up a CDN with an SPA when you access the site via the FrontDoor Url you are denied access and presented with an error page the the website has not been enabled 

## Possible Solution
A workaround is available to manually enable Static website hosting on the storage account manually 

<img width="694" alt="Screen Shot 2020-06-30 at 11 51 05" src="https://user-images.githubusercontent.com/16523764/86073855-0054bb80-bac8-11ea-8eed-1a976cfdcd4e.png">

## Steps to Reproduce (for bugs)
1. Deploy CDN with an SPA as the default route
2. once deployed access the site using the front door Url

## Context
Application content is unavailable 

## Your Environment
Hamlet Version: latest

**Comment by roleyfoley** [comment]
This should be completed @roleyfoley or @RossMurr4y  to confirm

**Comment by RossMurr4y** [comment]
This looks to be only possible currently through the CLI, using the following command:

```
az storage blob service-properties update --account-name <storage-account-name> --static-website true --404-document <error-document-name> --index-document <index-document-name>
```

See: https://docs.microsoft.com/en-au/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-cli

A prologue section could be added to the `cdn` setup implementation. During link processing on Routes, when linked to an SPA, it should retrieve the storage account config from the SPA and generate a prologue that on update performs the above action, and on delete performs the same, but with `--static-website false` & removes the documents.

**Comment by RossMurr4y** [comment]
Marking as good first issue as isn't an overly complex change.
