### ISSUE TITLE
Provider Component Support: db 

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-plugin-azure#29]
The [Db](https://github.com/codeontap/gen3/blob/fd8b073eee80fe3524ee5c3dd9cdf7a217a44024/providers/shared/components/db/id.ftl) provides a managed SQL based database using the cloud providers management services. 

When provisioned the Db component should offer other components the necessary information required to connect to the database instance, such as login details and endpoints. 

The endpoint should be part of the private network (#25) by default 

Automated backup services and version management, if they are available from the cloud provider should be able made available through configuration

High Availability should be configured based on the `MultiAz` configuration of the Environment/Product configuration to ensure cost management of the environment is being maintained.

Restoration of snapshots, if available from the provider should also be available as part of the CodeOnTap deployment process 

For AWS we currently use amazon RDS ( https://aws.amazon.com/rds/ ) and have support for the `postgres` and `mysql` database engines

**Comment by roleyfoley** [comment]
@RossMurr4y Can you please confirm this has been done

**Comment by RossMurr4y** [comment]
Confirmed done, and have existing tickets (linked) that fill in the expected gaps.
Closing.
