### ISSUE TITLE
KeyVault Reference Lookup Resource

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine-plugin-azure#72]
A number of components will make use of stored KeyVault secrets during their deployments. As an example, during the baseline component deployment a virtual machine SSH keypair is generated and imported into KeyVault as a secret. The creation of a Bastion component will consume the public key of this keypair during its deployment of a VM Scale Set. So we need a way to reference the KeyVault secrets within ARM templates.

This is accomplished by during the passing of a parameters object to a template. We could do that with nested templates, however it seems tidier to instead generate a parameters file for the template we're already outputting, and pass those parameters into the template. Example of how this is performed is below.

To implement these in the Azure plugin effectively we will require the following:

- [ ] Azure utility function in bash that will get a secret with az cli,
- [ ] and save a parameter file
- [ ] a freemarker function in the keyvault service that will create a prologue script (which uses the bash functions).
- [x] a freemarker function that adds to the parameter section of the template outputs (armParameter - like armOutput but for the parameters section.
- [x] updates to the macro arm_output_resource that will add any necessary parameters into the template file.

Example of a correctly formatted parameters file, with a call to KeyVault to retrieve a secret.
``` json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "sshPublicKey": {
            "reference": {
                "keyVault": {
                    "id": "/subscriptions/{subscription-id}/resourcegroups/{resource-group-name}/providers/Microsoft.KeyVault/vaults/{vault-name}"
                },
                "secretName": "<secret-name>"
            }
        }
    }
}
```

Example of an updated template file, accepting those parameters and then referencing them within a resource:
``` json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "sshPublicKey": {
        "type": "securestring"
      }
    },
    "variables": {},
    "resources": [
      {
        "name": "vmss-management-ssh-bastion",
        "type": "Microsoft.Compute/virtualMachineScaleSets",
        "apiVersion": "2019-03-01",
        "properties": {
          "upgradePolicy": {
            "mode": "Manual"
          },
          "virtualMachineProfile": {
            "osProfile": {
              "computerNamePrefix": "bastion",
              "adminUsername": "bastion",
              "linuxConfiguration": {
                "ssh": {
                  "publicKeys": [
                    { 
                      "path": "/home/bastion/.ssh/authorized_keys",
                      "keyData": "[parameters('sshPublicKey')]"
                    }
                  ]
                },
                "disablePasswordAuthentication": true
              }
            },
            "storageProfile": {...},
            "networkProfile": {...},
            "priority": "Regular"
          }
        },
        "identity": {...,
        "location": "eastus",
        "sku": {...}
      }
    ],
    "outputs": {...}
  }
  
```
Example is shortened for clarity.

**Comment by roleyfoley** [comment]
Can we use our existing getExistingReference/link functions for this? 

The intention of this setup is to share ids and resource references between components without having to have explicit references within templates between components. 
I can see benefit in using the cloud providers methods but it does have the potential to cause issues between multiple subscriptions and can make cross provider interesting

**Comment by RossMurr4y** [comment]
Updated to our latest discussion - not using nested resources but instead creating a typical parameters file through a prologue script.

**Comment by roleyfoley** [comment]
Now that we have #1167 manage deployment will need to be updated to check for the parameters file being present and use it 

You'll also need to add a new variable in the setStackContext 
https://github.com/codeontap/gen3/blob/5f21d7f8e3be72d050a12302d65dbad65c936f4a/execution/setStackContext.sh#L178 

This is used to reference files generated by create template in manage stack. in manage deployment you can reference the parameters file using the environment variable "${PARAMETERS}" if you add that to setStackContext

**Comment by RossMurr4y** [comment]
I have added these in PR codeontap/gen3#1170.

**Comment by RossMurr4y** [comment]
This has been implemented via the macro `armParameter` that adds a parameter input to the ARM template during the "template" pass. During a separate "parameter" pass, the macro `addParametersToDefaultJsonOutput` can be used to create the parameters file, and finally the function `getKeyVaultParameter()` will format a parameter property in such a way then when the ARM deployment is performed with both parameter file and template, the keyvault lookup is performed.

This issue is now resolved.
